# Generated by Django 5.2.1 on 2026-05-29 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livraisons', '0004_paiement_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='livraisons.livraison')),
                ('participants', models.ManyToManyField(help_text='Gestionnaire, Client, Livreur assigné', related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ks_messages_conversation',
                'ordering': ['-date_derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'db_table': 'ks_messages_message',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='LectureMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(auto_now_add=True)),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='conversations.message')),
            ],
            options={
                'db_table': 'ks_messages_lecture_message',
                'unique_together': {('message', 'lecteur')},
            },
        ),
    ]
