# Generated by Django 5.2.1 on 2026-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('LIVREUR', 'Livreur')], default='GESTIONNAIRE', max_length=32),
        ),
    ]
