# Generated by Django 5.2.1 on 2026-05-29 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_suppression_role_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('LIVREUR', 'Livreur'), ('CLIENT', 'Client')], default='GESTIONNAIRE', max_length=32),
        ),
        migrations.CreateModel(
            name='ProfilClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_premiere_livraison', models.DateTimeField(blank=True, null=True)),
                ('total_livraisons', models.IntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ks_utilisateurs_client',
            },
        ),
    ]
