# Generated by Django 6.0.5 on 2026-05-21 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ks_livraisons_historique',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_livraison', models.CharField(max_length=10, unique=True)),
                ('adresse_depart', models.TextField()),
                ('quartier_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_arrivee', models.TextField()),
                ('quartier_arrivee', models.CharField(blank=True, max_length=100, null=True)),
                ('point_repere', models.TextField(blank=True, null=True)),
                ('latitude_arrivee', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_arrivee', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description_colis', models.TextField()),
                ('type_colis', models.CharField(choices=[('DOCUMENT', 'Document'), ('ALIMENTAIRE', 'Alimentaire'), ('FRAGILE', 'Fragile'), ('STANDARD', 'Standard'), ('VOLUMINEUX', 'Volumineux')], default='STANDARD', max_length=20)),
                ('poids_estime_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('est_fragile', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ASSIGNEE', 'Assignée'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('ECHOUEE', 'Échec de livraison')], default='EN_ATTENTE', max_length=20)),
                ('cout_estime', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cout_final', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('mode_paiement', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN MoMo'), ('ESPECES', 'Espèces')], default='ESPECES', max_length=10)),
                ('est_paye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_assignation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('code_confirmation', models.CharField(blank=True, max_length=6, null=True)),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to='preuves/')),
                ('notes_livreur', models.TextField(blank=True, null=True)),
                ('note_client', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'ks_livraisons_livraison',
                'ordering': ['-date_creation'],
            },
        ),
    ]
