# Generated by Django 6.0.5 on 2026-05-22 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0002_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='duree_estimee_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='latitude_depart',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='longitude_depart',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ASSIGNEE', 'Assignée'), ('EN_ROUTE', 'En route'), ('EN_COURS', 'En cours'), ('PROCHE_DESTINATION', 'Proche destination'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('ECHOUEE', 'Échec de livraison')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PositionLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('progression', models.PositiveSmallIntegerField(default=0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('livraison_en_cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_livreur', to='livraisons.livraison')),
                ('livreur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_gps', to='utilisateurs.profillivreur')),
            ],
            options={
                'db_table': 'ks_livraisons_position_livreur',
            },
        ),
    ]
