# Generated by Django 6.0.5 on 2026-05-22 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0003_gps_position_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN MoMo')], max_length=10)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='livraisons.livraison')),
            ],
            options={
                'db_table': 'ks_livraisons_paiement_mobile',
            },
        ),
    ]
