# Generated by Django 5.2.1 on 2026-06-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0004_paiement_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementmobile',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paiementmobile',
            name='reference',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='paiementmobile',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Confirmé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=15),
        ),
    ]
