# Generated by Django 5.2.1 on 2026-06-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0005_paiementmobile_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ASSIGNEE', 'Assignée'), ('EN_ROUTE', 'En route'), ('EN_COURS', 'En cours'), ('PROCHE_DESTINATION', 'Proche destination'), ('ARRIVEE', 'Arrivée'), ('LIVREE', 'Livrée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée'), ('ECHOUEE', 'Échec de livraison')], default='EN_ATTENTE', max_length=20),
        ),
    ]
