# Generated by Django 6.0.5 on 2026-05-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('ASSIGNEE', 'Livraison assignée'), ('EN_COURS', 'Livraison en cours'), ('TERMINEE', 'Livraison terminée'), ('ANNULEE', 'Livraison annulée'), ('SYSTEME', 'Notification système'), ('ALERTE', 'Alerte administrateur')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ks_notifications_notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
